<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title ?? 'System Report' }}</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            margin: 30px;
            color: #333;
        }

        h2 {
            text-align: center;
            margin-bottom: 5px;
        }

        .meta-box {
            border: 1px solid #ccc;
            padding: 10px;
            margin-bottom: 20px;
            background-color: #f9f9f9;
        }

        .meta-box p {
            margin: 4px 0;
        }

        .filters {
            margin-top: 10px;
        }

        .filters ul {
            padding-left: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th, td {
            border: 1px solid #000;
            padding: 6px;
            text-align: left;
            word-wrap: break-word;
        }

        th {
            background-color: #eaeaea;
        }

        tr:nth-child(even) {
            background-color: #f6f6f6;
        }

        .no-records {
            text-align: center;
            font-style: italic;
            color: #888;
        }
    </style>
</head>
<body>
    <h2>{{ $title ?? 'System Report' }}</h2>

    <div class="meta-box">
        <p><strong>Generated on:</strong> {{ now()->format('M d, Y H:i') }}</p>
        <p><strong>Generated by:</strong> {{ auth()->user()->fname ?? 'System' }}</p>

        @if(!empty($filters['from_date']) || !empty($filters['to_date']))
            <p>
                <strong>Date Range:</strong>
                {{ !empty($filters['from_date']) ? \Carbon\Carbon::parse($filters['from_date'])->format('M d, Y') : 'N/A' }}
                —
                {{ !empty($filters['to_date']) ? \Carbon\Carbon::parse($filters['to_date'])->format('M d, Y') : 'N/A' }}
            </p>
        @endif
    </div>

    <table>
        <thead>
            <tr>
                @foreach($columns as $column)
                    <th>{{ ucfirst(str_replace('_', ' ', $column)) }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse($data as $item)
                <tr>
                    @foreach($columns as $column)
                        <td>{{ data_get($item, $column, '—') }}</td>
                    @endforeach
                </tr>
            @empty
                <tr>
                    <td colspan="{{ count($columns) }}" class="no-records">No records found</td>
                </tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>